# Generated by Django 3.1.7 on 2021-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_auto_20210417_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
